version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./out:/usr/src/app/out
      - ./src:/usr/src/app/src
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/geospatial_db

  db:
    image: postgis/postgis:13-3.1
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=geospatial_db
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  out: